
sudo: required
language: java

jdk:
  # DS-3384 Oracle JDK 8 has DocLint enabled by default.
  # Let's use this to catch any newly introduced DocLint issues.
  - oraclejdk8

## Should we run into any problems with oraclejdk8 on Travis, we may try the following workaround.


script:
  - mvn clean cobertura:cobertura -Dtest=DSpaceKernelServletContextListenerTest#testSampleRequestDouble -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/DSpace/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "eLHG9y++0AhakdgY944VujFLDP8yOCgJRe2cLKLBClW/c5cet1s/b4EJllnTZzMl8UOSCGjEEjzw3mvIVq+55j4ngtOqfE9l4pXfWJfaf4s/RdxGqGlYPDTMOCGWcOq5D4UvqeyqP2Um6FOqh7OJRE3uHs6x8cNPiNvQQivlSWF/mgcK3G6Bv8pUFa9j5HF3miF4JELRzN1ENyCjxA/bh9nkeLpRDSm7ceaIeWwoATH1ZvAkV1tWT4rdCwhyFInBhfuow8VmYfZ6rKxq84U5/Tt3b/2yJeB0LkQD85pvYIrD1pHCY3baPlZoxyYjki2xi8IYrKinhBNSm4Fm1T/ep08QW1T2dG8ahAOSEIaYweGGe+dXDN8srNNda744HAOE3DwTDeVBBzTvhlf4tQDixiq2yZVWM8KPgBZ++Q8y+GROFjfPQ57pnv2kdM0Bp2x0eKlD1EfqVvpLDQDtW3MaJQR+ggbSme9d5xom3aZQ+l24r+6+aWqmXP16o1Yc/h8ZlRkU/aSHmH4TqOiLUvaLeZ18/TJQ5HVaHWcmsO1q8dfRDb/Pd3nwVHSAZ/Y1RUbS5E0tGkz9WxbM+73d1t37w7E7zqJH5QcGVLbjbCiDziGWfie7M9DtQ/hpZjZNMWFs+YtCh0kQUpDW1UpLlMlO+7TZc1NVi8/DNPNv8QiNYVg="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
